# Databricks notebook source
# MAGIC %run ./05_agent_tools

# COMMAND ----------

def research_agent(user_request):

    request_lower = user_request.lower()

    # Retrieve a real paper first
    retrieved_paper = search_papers(
        "retrieval augmented generation",
        top_k=1
    )[0]

    paper_id = retrieved_paper["paper_id"]

    # Save Learning Goal
    if "save goal" in request_lower:

        result = save_learning_goal(
            "Learn Retrieval Augmented Generation"
        )

        return {
            "action": "save_learning_goal",
            "reason": "The user requested to save a learning goal.",
            "result": result
        }

    # Add Paper to Collection
    elif "add paper" in request_lower:

        result = add_to_collection(
            paper_id=paper_id,
            collection_name="Agent Collection"
        )

        return {
            "action": "add_to_collection",
            "reason": "The user requested to add a paper to a collection.",
            "paper_id": paper_id,
            "result": result
        }

    # Mark Completed
    elif "mark completed" in request_lower:

        result = mark_completed(
            paper_id
        )

        return {
            "action": "mark_completed",
            "reason": "The user requested to update reading progress.",
            "paper_id": paper_id,
            "result": result
        }

    # Save Note
    elif "save note" in request_lower:

        result = save_note(
            paper_id,
            "Important research note generated by the agent."
        )

        return {
            "action": "save_note",
            "reason": "The user requested to save a research note.",
            "paper_id": paper_id,
            "result": result
        }

    # Generate Study Plan
    elif "learn" in request_lower or "study plan" in request_lower:

        result = generate_study_plan(user_request)

        return {
            "action": "generate_study_plan",
            "reason": "The request appears to be a learning goal.",
            "result": result
        }

    # Search Papers
    else:

        result = search_papers(user_request)

        return {
            "action": "search_papers",
            "reason": "The request appears to be searching for research papers.",
            "result": result
        }

# COMMAND ----------

research_agent("save goal")

# COMMAND ----------

research_agent("add paper")

# COMMAND ----------

research_agent("mark completed")

# COMMAND ----------

research_agent("save note")

# COMMAND ----------

research_agent(
    "Learn Retrieval-Augmented Generation"
)

# COMMAND ----------

research_agent(
    "Find research papers about RAG evaluation"
)